//! Event and CustomEvent Implementation for Boa
//!
//! Full Event implementation with bubbling, capturing, and propagation control.

use std::cell::RefCell;

use boa_engine::{
    Context, JsObject, JsResult, JsValue, js_string,
};

use crate::codegen::types::ToJsValueBoa;

/// Event phases
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventPhase {
    None = 0,
    Capturing = 1,
    AtTarget = 2,
    Bubbling = 3,
}

impl Default for EventPhase {
    fn default() -> Self {
        EventPhase::None
    }
}

/// Event initialization options
#[derive(Debug, Clone, Default)]
pub struct EventInit {
    pub bubbles: bool,
    pub cancelable: bool,
    pub composed: bool,
}

/// Full Event implementation per DOM spec
#[derive(Clone)]
pub struct Event {
    /// Event type (e.g., "click", "keydown")
    event_type: String,
    
    /// Target of the event
    target: RefCell<Option<JsObject>>,
    
    /// Current target during dispatch
    current_target: RefCell<Option<JsObject>>,
    
    /// Related target (for mouse events, focus events, etc.)
    related_target: RefCell<Option<JsObject>>,
    
    /// Event phase
    event_phase: RefCell<EventPhase>,
    
    /// Whether event bubbles
    bubbles: bool,
    
    /// Whether event is cancelable
    cancelable: bool,
    
    /// Whether event is composed (crosses shadow DOM boundaries)
    composed: bool,
    
    /// Whether default was prevented
    default_prevented: RefCell<bool>,
    
    /// Whether propagation was stopped
    stop_propagation_flag: RefCell<bool>,
    
    /// Whether immediate propagation was stopped
    stop_immediate_propagation_flag: RefCell<bool>,
    
    /// Whether event was dispatched
    dispatched: RefCell<bool>,
    
    /// Whether event was initialized
    _initialized: bool,
    
    /// Whether event is trusted (generated by user agent)
    is_trusted: bool,
    
    /// Timestamp when event was created
    time_stamp: f64,
}

impl Event {
    /// Create a new Event
    pub fn new(event_type: &str) -> Self {
        Self::new_with_options(event_type, EventInit::default())
    }

    /// Create a new Event with options
    pub fn new_with_options(event_type: &str, init: EventInit) -> Self {
        Event {
            event_type: event_type.to_string(),
            target: RefCell::new(None),
            current_target: RefCell::new(None),
            related_target: RefCell::new(None),
            event_phase: RefCell::new(EventPhase::None),
            bubbles: init.bubbles,
            cancelable: init.cancelable,
            composed: init.composed,
            default_prevented: RefCell::new(false),
            stop_propagation_flag: RefCell::new(false),
            stop_immediate_propagation_flag: RefCell::new(false),
            dispatched: RefCell::new(false),
            _initialized: true,
            is_trusted: false,
            time_stamp: js_sys_now(),
        }
    }

    // === Getters ===

    /// Get event type
    pub fn event_type(&self) -> &str {
        &self.event_type
    }

    /// Alias for event_type (DOM spec uses "type")
    pub fn type_(&self) -> &str {
        &self.event_type
    }

    /// Get target
    pub fn target(&self) -> Option<JsObject> {
        self.target.borrow().clone()
    }

    /// Get current target
    pub fn current_target(&self) -> Option<JsObject> {
        self.current_target.borrow().clone()
    }

    /// Get related target
    pub fn related_target(&self) -> Option<JsObject> {
        self.related_target.borrow().clone()
    }

    /// Get event phase
    pub fn event_phase(&self) -> EventPhase {
        *self.event_phase.borrow()
    }

    /// Get bubbles
    pub fn bubbles(&self) -> bool {
        self.bubbles
    }

    /// Get cancelable
    pub fn cancelable(&self) -> bool {
        self.cancelable
    }

    /// Get composed
    pub fn composed(&self) -> bool {
        self.composed
    }

    /// Get defaultPrevented
    pub fn default_prevented(&self) -> bool {
        *self.default_prevented.borrow()
    }

    /// Get isTrusted
    pub fn is_trusted(&self) -> bool {
        self.is_trusted
    }

    /// Get timeStamp
    pub fn time_stamp(&self) -> f64 {
        self.time_stamp
    }

    // === Setters (for dispatch algorithm) ===

    /// Set target
    pub fn set_target(&self, target: Option<JsObject>) {
        *self.target.borrow_mut() = target;
    }

    /// Set current target
    pub fn set_current_target(&self, target: Option<JsObject>) {
        *self.current_target.borrow_mut() = target;
    }

    /// Set related target
    pub fn set_related_target(&self, target: Option<JsObject>) {
        *self.related_target.borrow_mut() = target;
    }

    /// Set event phase
    pub fn set_event_phase(&self, phase: EventPhase) {
        *self.event_phase.borrow_mut() = phase;
    }

    /// Mark as dispatched
    pub fn set_dispatched(&self, dispatched: bool) {
        *self.dispatched.borrow_mut() = dispatched;
    }

    /// Check if dispatched
    pub fn is_dispatched(&self) -> bool {
        *self.dispatched.borrow()
    }

    // === Methods ===

    /// Prevent default action
    pub fn prevent_default(&self) {
        if self.cancelable {
            *self.default_prevented.borrow_mut() = true;
        }
    }

    /// Stop propagation
    pub fn stop_propagation(&self) {
        *self.stop_propagation_flag.borrow_mut() = true;
    }

    /// Stop immediate propagation
    pub fn stop_immediate_propagation(&self) {
        *self.stop_propagation_flag.borrow_mut() = true;
        *self.stop_immediate_propagation_flag.borrow_mut() = true;
    }

    /// Check if propagation was stopped
    pub fn propagation_stopped(&self) -> bool {
        *self.stop_propagation_flag.borrow()
    }

    /// Check if immediate propagation was stopped
    pub fn immediate_propagation_stopped(&self) -> bool {
        *self.stop_immediate_propagation_flag.borrow()
    }

    /// Get composedPath (returns array of targets)
    pub fn composed_path(&self) -> Vec<JsObject> {
        // Simplified - would need full shadow DOM support
        if let Some(target) = self.target() {
            vec![target]
        } else {
            vec![]
        }
    }

    /// Initialize event (legacy method)
    pub fn init_event(&mut self, type_: &str, bubbles: bool, cancelable: bool) {
        if !self.is_dispatched() {
            *self.stop_propagation_flag.borrow_mut() = false;
            *self.stop_immediate_propagation_flag.borrow_mut() = false;
            *self.default_prevented.borrow_mut() = false;
            self.event_type = type_.to_string();
            // Note: bubbles and cancelable are immutable after construction in modern spec
        }
        let _ = bubbles;
        let _ = cancelable;
    }

    /// Create a trusted event (for user agent use)
    pub fn new_trusted(event_type: &str, init: EventInit) -> Self {
        let mut event = Self::new_with_options(event_type, init);
        event.is_trusted = true;
        event
    }
}

impl Default for Event {
    fn default() -> Self {
        Event::new("")
    }
}

impl ToJsValueBoa for Event {
    fn to_js_value(&self, ctx: &mut Context) -> JsResult<JsValue> {
        let obj = JsObject::with_null_proto();
        
        obj.set(js_string!("type"), JsValue::from(js_string!(self.event_type.as_str())), false, ctx)?;
        obj.set(js_string!("bubbles"), JsValue::from(self.bubbles), false, ctx)?;
        obj.set(js_string!("cancelable"), JsValue::from(self.cancelable), false, ctx)?;
        obj.set(js_string!("composed"), JsValue::from(self.composed), false, ctx)?;
        obj.set(js_string!("defaultPrevented"), JsValue::from(self.default_prevented()), false, ctx)?;
        obj.set(js_string!("isTrusted"), JsValue::from(self.is_trusted), false, ctx)?;
        obj.set(js_string!("timeStamp"), JsValue::from(self.time_stamp), false, ctx)?;
        obj.set(js_string!("eventPhase"), JsValue::from(self.event_phase() as i32), false, ctx)?;
        
        // target and currentTarget
        if let Some(target) = self.target() {
            obj.set(js_string!("target"), JsValue::from(target), false, ctx)?;
        } else {
            obj.set(js_string!("target"), JsValue::null(), false, ctx)?;
        }
        
        if let Some(current_target) = self.current_target() {
            obj.set(js_string!("currentTarget"), JsValue::from(current_target), false, ctx)?;
        } else {
            obj.set(js_string!("currentTarget"), JsValue::null(), false, ctx)?;
        }

        // Event phase constants
        obj.set(js_string!("NONE"), JsValue::from(0), false, ctx)?;
        obj.set(js_string!("CAPTURING_PHASE"), JsValue::from(1), false, ctx)?;
        obj.set(js_string!("AT_TARGET"), JsValue::from(2), false, ctx)?;
        obj.set(js_string!("BUBBLING_PHASE"), JsValue::from(3), false, ctx)?;

        Ok(JsValue::from(obj))
    }
}

// ============================================================================
// CustomEvent
// ============================================================================

/// CustomEvent initialization options
#[derive(Debug, Clone, Default)]
pub struct CustomEventInit {
    pub bubbles: bool,
    pub cancelable: bool,
    pub composed: bool,
    pub detail: Option<JsValue>,
}

/// CustomEvent - event with custom data
pub struct CustomEvent {
    /// Base event
    event: Event,
    
    /// Custom detail data
    detail: RefCell<JsValue>,
}

impl CustomEvent {
    /// Create a new CustomEvent
    pub fn new(event_type: &str) -> Self {
        CustomEvent {
            event: Event::new(event_type),
            detail: RefCell::new(JsValue::null()),
        }
    }

    /// Create a new CustomEvent with options
    pub fn new_with_options(event_type: &str, init: CustomEventInit) -> Self {
        let event_init = EventInit {
            bubbles: init.bubbles,
            cancelable: init.cancelable,
            composed: init.composed,
        };
        
        CustomEvent {
            event: Event::new_with_options(event_type, event_init),
            detail: RefCell::new(init.detail.unwrap_or(JsValue::null())),
        }
    }

    /// Get the base event
    pub fn event(&self) -> &Event {
        &self.event
    }

    /// Get the detail
    pub fn detail(&self) -> JsValue {
        self.detail.borrow().clone()
    }

    /// Set the detail
    pub fn set_detail(&self, detail: JsValue) {
        *self.detail.borrow_mut() = detail;
    }

    /// Initialize custom event (legacy method)
    pub fn init_custom_event(
        &mut self,
        type_: &str,
        bubbles: bool,
        cancelable: bool,
        detail: JsValue,
    ) {
        self.event.init_event(type_, bubbles, cancelable);
        if !self.event.is_dispatched() {
            *self.detail.borrow_mut() = detail;
        }
    }
}

impl ToJsValueBoa for CustomEvent {
    fn to_js_value(&self, ctx: &mut Context) -> JsResult<JsValue> {
        // Get base event as object
        let base = self.event.to_js_value(ctx)?;
        let obj = base.as_object()
            .map(|o| o.clone())
            .unwrap_or_else(JsObject::with_null_proto);
        
        // Add detail property
        obj.set(js_string!("detail"), self.detail(), false, ctx)?;
        
        Ok(JsValue::from(obj))
    }
}

// ============================================================================
// Common Event Types
// ============================================================================

/// Mouse event data
#[derive(Clone, Default)]
pub struct MouseEventInit {
    pub event_init: EventInit,
    pub screen_x: i32,
    pub screen_y: i32,
    pub client_x: i32,
    pub client_y: i32,
    pub ctrl_key: bool,
    pub shift_key: bool,
    pub alt_key: bool,
    pub meta_key: bool,
    pub button: i16,
    pub buttons: u16,
    pub related_target: Option<JsObject>,
}

/// MouseEvent
pub struct MouseEvent {
    event: Event,
    screen_x: i32,
    screen_y: i32,
    client_x: i32,
    client_y: i32,
    ctrl_key: bool,
    shift_key: bool,
    alt_key: bool,
    meta_key: bool,
    button: i16,
    buttons: u16,
}

impl MouseEvent {
    pub fn new(event_type: &str) -> Self {
        MouseEvent {
            event: Event::new(event_type),
            screen_x: 0,
            screen_y: 0,
            client_x: 0,
            client_y: 0,
            ctrl_key: false,
            shift_key: false,
            alt_key: false,
            meta_key: false,
            button: 0,
            buttons: 0,
        }
    }

    pub fn new_with_options(event_type: &str, init: MouseEventInit) -> Self {
        let event = Event::new_with_options(event_type, init.event_init);
        event.set_related_target(init.related_target);
        
        MouseEvent {
            event,
            screen_x: init.screen_x,
            screen_y: init.screen_y,
            client_x: init.client_x,
            client_y: init.client_y,
            ctrl_key: init.ctrl_key,
            shift_key: init.shift_key,
            alt_key: init.alt_key,
            meta_key: init.meta_key,
            button: init.button,
            buttons: init.buttons,
        }
    }

    pub fn event(&self) -> &Event { &self.event }
    pub fn screen_x(&self) -> i32 { self.screen_x }
    pub fn screen_y(&self) -> i32 { self.screen_y }
    pub fn client_x(&self) -> i32 { self.client_x }
    pub fn client_y(&self) -> i32 { self.client_y }
    pub fn page_x(&self) -> i32 { self.client_x } // Simplified
    pub fn page_y(&self) -> i32 { self.client_y } // Simplified
    pub fn offset_x(&self) -> i32 { self.client_x } // Simplified
    pub fn offset_y(&self) -> i32 { self.client_y } // Simplified
    pub fn ctrl_key(&self) -> bool { self.ctrl_key }
    pub fn shift_key(&self) -> bool { self.shift_key }
    pub fn alt_key(&self) -> bool { self.alt_key }
    pub fn meta_key(&self) -> bool { self.meta_key }
    pub fn button(&self) -> i16 { self.button }
    pub fn buttons(&self) -> u16 { self.buttons }
}

impl ToJsValueBoa for MouseEvent {
    fn to_js_value(&self, ctx: &mut Context) -> JsResult<JsValue> {
        let base = self.event.to_js_value(ctx)?;
        let obj = base.as_object()
            .map(|o| o.clone())
            .unwrap_or_else(JsObject::with_null_proto);
        
        obj.set(js_string!("screenX"), JsValue::from(self.screen_x), false, ctx)?;
        obj.set(js_string!("screenY"), JsValue::from(self.screen_y), false, ctx)?;
        obj.set(js_string!("clientX"), JsValue::from(self.client_x), false, ctx)?;
        obj.set(js_string!("clientY"), JsValue::from(self.client_y), false, ctx)?;
        obj.set(js_string!("pageX"), JsValue::from(self.page_x()), false, ctx)?;
        obj.set(js_string!("pageY"), JsValue::from(self.page_y()), false, ctx)?;
        obj.set(js_string!("offsetX"), JsValue::from(self.offset_x()), false, ctx)?;
        obj.set(js_string!("offsetY"), JsValue::from(self.offset_y()), false, ctx)?;
        obj.set(js_string!("ctrlKey"), JsValue::from(self.ctrl_key), false, ctx)?;
        obj.set(js_string!("shiftKey"), JsValue::from(self.shift_key), false, ctx)?;
        obj.set(js_string!("altKey"), JsValue::from(self.alt_key), false, ctx)?;
        obj.set(js_string!("metaKey"), JsValue::from(self.meta_key), false, ctx)?;
        obj.set(js_string!("button"), JsValue::from(self.button), false, ctx)?;
        obj.set(js_string!("buttons"), JsValue::from(self.buttons), false, ctx)?;
        
        Ok(JsValue::from(obj))
    }
}

/// Keyboard event data
#[derive(Clone, Default)]
pub struct KeyboardEventInit {
    pub event_init: EventInit,
    pub key: String,
    pub code: String,
    pub location: u32,
    pub ctrl_key: bool,
    pub shift_key: bool,
    pub alt_key: bool,
    pub meta_key: bool,
    pub repeat: bool,
    pub is_composing: bool,
}

/// KeyboardEvent
pub struct KeyboardEvent {
    event: Event,
    key: String,
    code: String,
    location: u32,
    ctrl_key: bool,
    shift_key: bool,
    alt_key: bool,
    meta_key: bool,
    repeat: bool,
    is_composing: bool,
}

impl KeyboardEvent {
    pub fn new(event_type: &str) -> Self {
        KeyboardEvent {
            event: Event::new(event_type),
            key: String::new(),
            code: String::new(),
            location: 0,
            ctrl_key: false,
            shift_key: false,
            alt_key: false,
            meta_key: false,
            repeat: false,
            is_composing: false,
        }
    }

    pub fn new_with_options(event_type: &str, init: KeyboardEventInit) -> Self {
        KeyboardEvent {
            event: Event::new_with_options(event_type, init.event_init),
            key: init.key,
            code: init.code,
            location: init.location,
            ctrl_key: init.ctrl_key,
            shift_key: init.shift_key,
            alt_key: init.alt_key,
            meta_key: init.meta_key,
            repeat: init.repeat,
            is_composing: init.is_composing,
        }
    }

    pub fn event(&self) -> &Event { &self.event }
    pub fn key(&self) -> &str { &self.key }
    pub fn code(&self) -> &str { &self.code }
    pub fn location(&self) -> u32 { self.location }
    pub fn ctrl_key(&self) -> bool { self.ctrl_key }
    pub fn shift_key(&self) -> bool { self.shift_key }
    pub fn alt_key(&self) -> bool { self.alt_key }
    pub fn meta_key(&self) -> bool { self.meta_key }
    pub fn repeat(&self) -> bool { self.repeat }
    pub fn is_composing(&self) -> bool { self.is_composing }

    pub fn get_modifier_state(&self, key: &str) -> bool {
        match key {
            "Control" => self.ctrl_key,
            "Shift" => self.shift_key,
            "Alt" => self.alt_key,
            "Meta" => self.meta_key,
            _ => false,
        }
    }
}

impl ToJsValueBoa for KeyboardEvent {
    fn to_js_value(&self, ctx: &mut Context) -> JsResult<JsValue> {
        let base = self.event.to_js_value(ctx)?;
        let obj = base.as_object()
            .map(|o| o.clone())
            .unwrap_or_else(JsObject::with_null_proto);
        
        obj.set(js_string!("key"), JsValue::from(js_string!(self.key.as_str())), false, ctx)?;
        obj.set(js_string!("code"), JsValue::from(js_string!(self.code.as_str())), false, ctx)?;
        obj.set(js_string!("location"), JsValue::from(self.location), false, ctx)?;
        obj.set(js_string!("ctrlKey"), JsValue::from(self.ctrl_key), false, ctx)?;
        obj.set(js_string!("shiftKey"), JsValue::from(self.shift_key), false, ctx)?;
        obj.set(js_string!("altKey"), JsValue::from(self.alt_key), false, ctx)?;
        obj.set(js_string!("metaKey"), JsValue::from(self.meta_key), false, ctx)?;
        obj.set(js_string!("repeat"), JsValue::from(self.repeat), false, ctx)?;
        obj.set(js_string!("isComposing"), JsValue::from(self.is_composing), false, ctx)?;
        
        // Location constants
        obj.set(js_string!("DOM_KEY_LOCATION_STANDARD"), JsValue::from(0), false, ctx)?;
        obj.set(js_string!("DOM_KEY_LOCATION_LEFT"), JsValue::from(1), false, ctx)?;
        obj.set(js_string!("DOM_KEY_LOCATION_RIGHT"), JsValue::from(2), false, ctx)?;
        obj.set(js_string!("DOM_KEY_LOCATION_NUMPAD"), JsValue::from(3), false, ctx)?;
        
        Ok(JsValue::from(obj))
    }
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Get current timestamp (simplified)
fn js_sys_now() -> f64 {
    // In a real implementation, would use std::time or js_sys
    0.0
}

/// Initialize Event prototype
pub fn init_event_prototype(context: &mut Context) -> JsResult<JsObject> {
    let prototype = JsObject::with_null_proto();

    // Properties
    prototype.set(js_string!("type"), JsValue::from(js_string!("")), false, context)?;
    prototype.set(js_string!("target"), JsValue::null(), false, context)?;
    prototype.set(js_string!("currentTarget"), JsValue::null(), false, context)?;
    prototype.set(js_string!("eventPhase"), JsValue::from(0), false, context)?;
    prototype.set(js_string!("bubbles"), JsValue::from(false), false, context)?;
    prototype.set(js_string!("cancelable"), JsValue::from(false), false, context)?;
    prototype.set(js_string!("defaultPrevented"), JsValue::from(false), false, context)?;
    prototype.set(js_string!("composed"), JsValue::from(false), false, context)?;
    prototype.set(js_string!("isTrusted"), JsValue::from(false), false, context)?;
    prototype.set(js_string!("timeStamp"), JsValue::from(0.0), false, context)?;

    // Phase constants
    prototype.set(js_string!("NONE"), JsValue::from(0), false, context)?;
    prototype.set(js_string!("CAPTURING_PHASE"), JsValue::from(1), false, context)?;
    prototype.set(js_string!("AT_TARGET"), JsValue::from(2), false, context)?;
    prototype.set(js_string!("BUBBLING_PHASE"), JsValue::from(3), false, context)?;

    // Methods (stubs)
    let empty_func = JsObject::with_null_proto();
    prototype.set(js_string!("preventDefault"), JsValue::from(empty_func.clone()), false, context)?;
    prototype.set(js_string!("stopPropagation"), JsValue::from(empty_func.clone()), false, context)?;
    prototype.set(js_string!("stopImmediatePropagation"), JsValue::from(empty_func.clone()), false, context)?;
    prototype.set(js_string!("composedPath"), JsValue::from(empty_func), false, context)?;

    Ok(prototype)
}

/// Initialize CustomEvent prototype
pub fn init_custom_event_prototype(context: &mut Context) -> JsResult<JsObject> {
    let prototype = init_event_prototype(context)?;
    
    // Add detail property
    prototype.set(js_string!("detail"), JsValue::null(), false, context)?;
    
    Ok(prototype)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_event_creation() {
        let event = Event::new("click");
        assert_eq!(event.type_(), "click");
        assert!(!event.bubbles());
        assert!(!event.cancelable());
    }

    #[test]
    fn test_event_with_options() {
        let event = Event::new_with_options("submit", EventInit {
            bubbles: true,
            cancelable: true,
            composed: false,
        });
        assert_eq!(event.type_(), "submit");
        assert!(event.bubbles());
        assert!(event.cancelable());
    }

    #[test]
    fn test_prevent_default() {
        let event = Event::new_with_options("click", EventInit {
            cancelable: true,
            ..Default::default()
        });
        assert!(!event.default_prevented());
        event.prevent_default();
        assert!(event.default_prevented());
    }

    #[test]
    fn test_prevent_default_not_cancelable() {
        let event = Event::new("load"); // Not cancelable
        event.prevent_default();
        assert!(!event.default_prevented()); // Should remain false
    }

    #[test]
    fn test_stop_propagation() {
        let event = Event::new("click");
        assert!(!event.propagation_stopped());
        event.stop_propagation();
        assert!(event.propagation_stopped());
    }

    #[test]
    fn test_stop_immediate_propagation() {
        let event = Event::new("click");
        assert!(!event.immediate_propagation_stopped());
        event.stop_immediate_propagation();
        assert!(event.immediate_propagation_stopped());
        assert!(event.propagation_stopped()); // Also stops regular propagation
    }

    #[test]
    fn test_event_phase() {
        let event = Event::new("click");
        assert_eq!(event.event_phase(), EventPhase::None);
        
        event.set_event_phase(EventPhase::Capturing);
        assert_eq!(event.event_phase(), EventPhase::Capturing);
        
        event.set_event_phase(EventPhase::AtTarget);
        assert_eq!(event.event_phase(), EventPhase::AtTarget);
        
        event.set_event_phase(EventPhase::Bubbling);
        assert_eq!(event.event_phase(), EventPhase::Bubbling);
    }

    #[test]
    fn test_custom_event() {
        let event = CustomEvent::new("myevent");
        assert_eq!(event.event().type_(), "myevent");
        assert!(event.detail().is_null());
    }

    #[test]
    fn test_custom_event_with_detail() {
        let event = CustomEvent::new_with_options("myevent", CustomEventInit {
            bubbles: true,
            detail: Some(JsValue::from(42)),
            ..Default::default()
        });
        assert!(event.event().bubbles());
        // Note: In a real test, we'd check the detail value
    }

    #[test]
    fn test_mouse_event() {
        let event = MouseEvent::new_with_options("click", MouseEventInit {
            event_init: EventInit { bubbles: true, cancelable: true, ..Default::default() },
            client_x: 100,
            client_y: 200,
            button: 0,
            ..Default::default()
        });
        assert_eq!(event.event().type_(), "click");
        assert_eq!(event.client_x(), 100);
        assert_eq!(event.client_y(), 200);
        assert_eq!(event.button(), 0);
    }

    #[test]
    fn test_keyboard_event() {
        let event = KeyboardEvent::new_with_options("keydown", KeyboardEventInit {
            event_init: EventInit { bubbles: true, cancelable: true, ..Default::default() },
            key: "Enter".to_string(),
            code: "Enter".to_string(),
            ctrl_key: true,
            ..Default::default()
        });
        assert_eq!(event.event().type_(), "keydown");
        assert_eq!(event.key(), "Enter");
        assert_eq!(event.code(), "Enter");
        assert!(event.ctrl_key());
        assert!(event.get_modifier_state("Control"));
    }

    #[test]
    fn test_trusted_event() {
        let event = Event::new_trusted("click", EventInit::default());
        assert!(event.is_trusted());
    }
}
