//! PrototypeList - Interface prototype identifiers for Boa bindings
//!
//! This module provides the equivalent of SpiderMonkey's generated PrototypeList.rs
//! but implemented directly in Rust for the Boa JS engine.
//!
//! In SpiderMonkey, this is generated by codegen.py from WebIDL definitions.
//! For Boa, we define a static set of interface IDs and provide runtime registration.

use std::sync::atomic::{AtomicUsize, Ordering};

/// Maximum length of the prototype chain for any interface.
/// This matches SpiderMonkey's MAX_PROTO_CHAIN_LENGTH.
pub const MAX_PROTO_CHAIN_LENGTH: usize = 8;

/// Counter for dynamically assigned prototype IDs
static NEXT_PROTO_ID: AtomicUsize = AtomicUsize::new(0);

/// Counter for dynamically assigned constructor IDs
static NEXT_CONSTRUCTOR_ID: AtomicUsize = AtomicUsize::new(0);

/// Get the next available prototype ID
pub fn allocate_proto_id() -> usize {
    NEXT_PROTO_ID.fetch_add(1, Ordering::SeqCst)
}

/// Get the next available constructor ID
pub fn allocate_constructor_id() -> usize {
    NEXT_CONSTRUCTOR_ID.fetch_add(1, Ordering::SeqCst)
}

/// Get the current count of registered prototypes
pub fn proto_count() -> usize {
    NEXT_PROTO_ID.load(Ordering::SeqCst)
}

/// Get the current count of registered constructors
pub fn constructor_count() -> usize {
    NEXT_CONSTRUCTOR_ID.load(Ordering::SeqCst)
}

/// Total number of prototype and interface slots (dynamic)
pub fn proto_or_iface_length() -> usize {
    proto_count() + constructor_count()
}

/// Interface prototype identifier.
/// 
/// In SpiderMonkey, ID is an enum with variants for each WebIDL interface.
/// In Boa, we use a newtype wrapper around usize for dynamic registration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(transparent)]
pub struct ID(pub u16);

impl ID {
    /// Special "Last" sentinel value indicating end of valid IDs
    pub const LAST: ID = ID(u16::MAX);
    
    /// Create a new prototype ID
    pub const fn new(value: u16) -> Self {
        ID(value)
    }
    
    /// Get the numeric value of this ID
    pub const fn as_u16(self) -> u16 {
        self.0
    }
    
    /// Check if this is the Last sentinel
    pub const fn is_last(self) -> bool {
        self.0 == u16::MAX
    }
}

impl From<u16> for ID {
    fn from(value: u16) -> Self {
        ID(value)
    }
}

impl From<ID> for u16 {
    fn from(id: ID) -> Self {
        id.0
    }
}

impl From<ID> for usize {
    fn from(id: ID) -> Self {
        id.0 as usize
    }
}

/// Constructor identifier for interfaces with constructors.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(transparent)]
pub struct Constructor(pub u16);

impl Constructor {
    /// Create a new constructor ID with offset from prototype IDs
    pub const fn new(value: u16) -> Self {
        Constructor(value)
    }
    
    /// Get the numeric value of this constructor ID
    pub const fn as_u16(self) -> u16 {
        self.0
    }
}

impl From<u16> for Constructor {
    fn from(value: u16) -> Self {
        Constructor(value)
    }
}

impl From<Constructor> for u16 {
    fn from(ctor: Constructor) -> Self {
        ctor.0
    }
}

impl From<Constructor> for usize {
    fn from(ctor: Constructor) -> Self {
        ctor.0 as usize
    }
}

/// Well-known interface IDs for core DOM interfaces.
/// These are statically defined for common interfaces that need
/// to be referenced by ID in the codebase.
pub mod well_known {
    use super::ID;
    
    // Base interfaces
    pub const EVENT_TARGET: ID = ID::new(0);
    pub const NODE: ID = ID::new(1);
    pub const ELEMENT: ID = ID::new(2);
    pub const HTML_ELEMENT: ID = ID::new(3);
    pub const DOCUMENT: ID = ID::new(4);
    pub const WINDOW: ID = ID::new(5);
    pub const TEXT: ID = ID::new(6);
    pub const COMMENT: ID = ID::new(7);
    pub const DOCUMENT_FRAGMENT: ID = ID::new(8);
    pub const ATTR: ID = ID::new(9);
    
    // Event types
    pub const EVENT: ID = ID::new(10);
    pub const UI_EVENT: ID = ID::new(11);
    pub const MOUSE_EVENT: ID = ID::new(12);
    pub const KEYBOARD_EVENT: ID = ID::new(13);
    pub const CUSTOM_EVENT: ID = ID::new(14);
    
    // Common HTML elements
    pub const HTML_DIV_ELEMENT: ID = ID::new(15);
    pub const HTML_SPAN_ELEMENT: ID = ID::new(16);
    pub const HTML_INPUT_ELEMENT: ID = ID::new(17);
    pub const HTML_BUTTON_ELEMENT: ID = ID::new(18);
    pub const HTML_FORM_ELEMENT: ID = ID::new(19);
    pub const HTML_ANCHOR_ELEMENT: ID = ID::new(20);
    pub const HTML_IMAGE_ELEMENT: ID = ID::new(21);
    pub const HTML_SCRIPT_ELEMENT: ID = ID::new(22);
    pub const HTML_STYLE_ELEMENT: ID = ID::new(23);
    pub const HTML_LINK_ELEMENT: ID = ID::new(24);
    
    // CSS interfaces
    pub const CSS_STYLE_DECLARATION: ID = ID::new(25);
    pub const CSS_RULE: ID = ID::new(26);
    pub const CSS_STYLE_SHEET: ID = ID::new(27);
    
    // Collections
    pub const NODE_LIST: ID = ID::new(28);
    pub const HTML_COLLECTION: ID = ID::new(29);
    pub const DOM_TOKEN_LIST: ID = ID::new(30);
    pub const NAMED_NODE_MAP: ID = ID::new(31);
    
    // Ranges and selection
    pub const RANGE: ID = ID::new(32);
    pub const SELECTION: ID = ID::new(33);
    
    // XMLHttpRequest
    pub const XML_HTTP_REQUEST: ID = ID::new(34);
    pub const XML_HTTP_REQUEST_EVENT_TARGET: ID = ID::new(35);
    
    // Promises and async
    pub const PROMISE: ID = ID::new(36);
    pub const ABORT_CONTROLLER: ID = ID::new(37);
    pub const ABORT_SIGNAL: ID = ID::new(38);
    
    // Storage
    pub const STORAGE: ID = ID::new(39);
    
    // Performance
    pub const PERFORMANCE: ID = ID::new(40);
    pub const PERFORMANCE_ENTRY: ID = ID::new(41);
    
    // URL
    pub const URL: ID = ID::new(42);
    pub const URL_SEARCH_PARAMS: ID = ID::new(43);
    
    // Console
    pub const CONSOLE: ID = ID::new(44);
    
    // Observers
    pub const MUTATION_OBSERVER: ID = ID::new(45);
    pub const INTERSECTION_OBSERVER: ID = ID::new(46);
    pub const RESIZE_OBSERVER: ID = ID::new(47);
    
    // Media
    pub const HTML_MEDIA_ELEMENT: ID = ID::new(48);
    pub const HTML_VIDEO_ELEMENT: ID = ID::new(49);
    pub const HTML_AUDIO_ELEMENT: ID = ID::new(50);
    pub const MEDIA_SOURCE: ID = ID::new(51);
    pub const SOURCE_BUFFER: ID = ID::new(52);
    
    // Canvas
    pub const HTML_CANVAS_ELEMENT: ID = ID::new(53);
    pub const CANVAS_RENDERING_CONTEXT_2D: ID = ID::new(54);
    pub const WEBGL_RENDERING_CONTEXT: ID = ID::new(55);
    pub const WEBGL2_RENDERING_CONTEXT: ID = ID::new(56);
    
    // Workers
    pub const WORKER: ID = ID::new(57);
    pub const SERVICE_WORKER: ID = ID::new(58);
    pub const SHARED_WORKER: ID = ID::new(59);
    
    // Web Audio
    pub const AUDIO_CONTEXT: ID = ID::new(60);
    pub const AUDIO_NODE: ID = ID::new(61);
    
    // Encoding
    pub const TEXT_ENCODER: ID = ID::new(62);
    pub const TEXT_DECODER: ID = ID::new(63);
    
    // Crypto
    pub const CRYPTO: ID = ID::new(64);
    pub const SUBTLE_CRYPTO: ID = ID::new(65);
    
    // Headers/Request/Response
    pub const HEADERS: ID = ID::new(66);
    pub const REQUEST: ID = ID::new(67);
    pub const RESPONSE: ID = ID::new(68);
    
    // Blob/File
    pub const BLOB: ID = ID::new(69);
    pub const FILE: ID = ID::new(70);
    pub const FILE_READER: ID = ID::new(71);
    pub const FILE_LIST: ID = ID::new(72);
    
    // Form Data
    pub const FORM_DATA: ID = ID::new(73);
    
    // WebSocket
    pub const WEB_SOCKET: ID = ID::new(74);
    
    // Starting ID for dynamically registered interfaces
    pub const FIRST_DYNAMIC: u16 = 75;
}

use std::sync::RwLock;
use std::collections::HashMap;

/// Global interface name registry for proto_id_to_name
static INTERFACE_NAMES: RwLock<Option<HashMap<u16, &'static str>>> = RwLock::new(None);

/// Initialize the well-known interface names
fn init_interface_names() -> HashMap<u16, &'static str> {
    let mut names = HashMap::new();
    
    names.insert(well_known::EVENT_TARGET.0, "EventTarget");
    names.insert(well_known::NODE.0, "Node");
    names.insert(well_known::ELEMENT.0, "Element");
    names.insert(well_known::HTML_ELEMENT.0, "HTMLElement");
    names.insert(well_known::DOCUMENT.0, "Document");
    names.insert(well_known::WINDOW.0, "Window");
    names.insert(well_known::TEXT.0, "Text");
    names.insert(well_known::COMMENT.0, "Comment");
    names.insert(well_known::DOCUMENT_FRAGMENT.0, "DocumentFragment");
    names.insert(well_known::ATTR.0, "Attr");
    names.insert(well_known::EVENT.0, "Event");
    names.insert(well_known::UI_EVENT.0, "UIEvent");
    names.insert(well_known::MOUSE_EVENT.0, "MouseEvent");
    names.insert(well_known::KEYBOARD_EVENT.0, "KeyboardEvent");
    names.insert(well_known::CUSTOM_EVENT.0, "CustomEvent");
    names.insert(well_known::HTML_DIV_ELEMENT.0, "HTMLDivElement");
    names.insert(well_known::HTML_SPAN_ELEMENT.0, "HTMLSpanElement");
    names.insert(well_known::HTML_INPUT_ELEMENT.0, "HTMLInputElement");
    names.insert(well_known::HTML_BUTTON_ELEMENT.0, "HTMLButtonElement");
    names.insert(well_known::HTML_FORM_ELEMENT.0, "HTMLFormElement");
    names.insert(well_known::HTML_ANCHOR_ELEMENT.0, "HTMLAnchorElement");
    names.insert(well_known::HTML_IMAGE_ELEMENT.0, "HTMLImageElement");
    names.insert(well_known::HTML_SCRIPT_ELEMENT.0, "HTMLScriptElement");
    names.insert(well_known::HTML_STYLE_ELEMENT.0, "HTMLStyleElement");
    names.insert(well_known::HTML_LINK_ELEMENT.0, "HTMLLinkElement");
    names.insert(well_known::CSS_STYLE_DECLARATION.0, "CSSStyleDeclaration");
    names.insert(well_known::CSS_RULE.0, "CSSRule");
    names.insert(well_known::CSS_STYLE_SHEET.0, "CSSStyleSheet");
    names.insert(well_known::NODE_LIST.0, "NodeList");
    names.insert(well_known::HTML_COLLECTION.0, "HTMLCollection");
    names.insert(well_known::DOM_TOKEN_LIST.0, "DOMTokenList");
    names.insert(well_known::NAMED_NODE_MAP.0, "NamedNodeMap");
    names.insert(well_known::RANGE.0, "Range");
    names.insert(well_known::SELECTION.0, "Selection");
    names.insert(well_known::XML_HTTP_REQUEST.0, "XMLHttpRequest");
    names.insert(well_known::XML_HTTP_REQUEST_EVENT_TARGET.0, "XMLHttpRequestEventTarget");
    names.insert(well_known::PROMISE.0, "Promise");
    names.insert(well_known::ABORT_CONTROLLER.0, "AbortController");
    names.insert(well_known::ABORT_SIGNAL.0, "AbortSignal");
    names.insert(well_known::STORAGE.0, "Storage");
    names.insert(well_known::PERFORMANCE.0, "Performance");
    names.insert(well_known::PERFORMANCE_ENTRY.0, "PerformanceEntry");
    names.insert(well_known::URL.0, "URL");
    names.insert(well_known::URL_SEARCH_PARAMS.0, "URLSearchParams");
    names.insert(well_known::CONSOLE.0, "console");
    names.insert(well_known::MUTATION_OBSERVER.0, "MutationObserver");
    names.insert(well_known::INTERSECTION_OBSERVER.0, "IntersectionObserver");
    names.insert(well_known::RESIZE_OBSERVER.0, "ResizeObserver");
    names.insert(well_known::HTML_MEDIA_ELEMENT.0, "HTMLMediaElement");
    names.insert(well_known::HTML_VIDEO_ELEMENT.0, "HTMLVideoElement");
    names.insert(well_known::HTML_AUDIO_ELEMENT.0, "HTMLAudioElement");
    names.insert(well_known::MEDIA_SOURCE.0, "MediaSource");
    names.insert(well_known::SOURCE_BUFFER.0, "SourceBuffer");
    names.insert(well_known::HTML_CANVAS_ELEMENT.0, "HTMLCanvasElement");
    names.insert(well_known::CANVAS_RENDERING_CONTEXT_2D.0, "CanvasRenderingContext2D");
    names.insert(well_known::WEBGL_RENDERING_CONTEXT.0, "WebGLRenderingContext");
    names.insert(well_known::WEBGL2_RENDERING_CONTEXT.0, "WebGL2RenderingContext");
    names.insert(well_known::WORKER.0, "Worker");
    names.insert(well_known::SERVICE_WORKER.0, "ServiceWorker");
    names.insert(well_known::SHARED_WORKER.0, "SharedWorker");
    names.insert(well_known::AUDIO_CONTEXT.0, "AudioContext");
    names.insert(well_known::AUDIO_NODE.0, "AudioNode");
    names.insert(well_known::TEXT_ENCODER.0, "TextEncoder");
    names.insert(well_known::TEXT_DECODER.0, "TextDecoder");
    names.insert(well_known::CRYPTO.0, "Crypto");
    names.insert(well_known::SUBTLE_CRYPTO.0, "SubtleCrypto");
    names.insert(well_known::HEADERS.0, "Headers");
    names.insert(well_known::REQUEST.0, "Request");
    names.insert(well_known::RESPONSE.0, "Response");
    names.insert(well_known::BLOB.0, "Blob");
    names.insert(well_known::FILE.0, "File");
    names.insert(well_known::FILE_READER.0, "FileReader");
    names.insert(well_known::FILE_LIST.0, "FileList");
    names.insert(well_known::FORM_DATA.0, "FormData");
    names.insert(well_known::WEB_SOCKET.0, "WebSocket");
    
    names
}

/// Register a new interface name for a prototype ID
pub fn register_interface_name(id: ID, name: &'static str) {
    let mut guard = INTERFACE_NAMES.write().unwrap();
    let names = guard.get_or_insert_with(init_interface_names);
    names.insert(id.0, name);
}

/// Get the interface name for a prototype ID.
/// Returns "Unknown" if the ID is not registered.
pub fn proto_id_to_name(proto_id: u16) -> &'static str {
    let guard = INTERFACE_NAMES.read().unwrap();
    if let Some(names) = guard.as_ref() {
        names.get(&proto_id).copied().unwrap_or("Unknown")
    } else {
        // Initialize lazily
        drop(guard);
        let mut write_guard = INTERFACE_NAMES.write().unwrap();
        let names = write_guard.get_or_insert_with(init_interface_names);
        names.get(&proto_id).copied().unwrap_or("Unknown")
    }
}

/// Interface chain for inheritance hierarchy.
/// 
/// Represents the prototype chain from most derived to base interface.
/// Padded with ID::LAST to MAX_PROTO_CHAIN_LENGTH.
#[derive(Debug, Clone, Copy)]
pub struct InterfaceChain {
    /// The chain of interface IDs, from most derived to base.
    /// Unused slots are filled with ID::LAST.
    pub chain: [ID; MAX_PROTO_CHAIN_LENGTH],
    /// The actual depth of the chain (number of valid IDs).
    pub depth: u8,
}

impl InterfaceChain {
    /// Create a new interface chain from a slice of IDs.
    /// The slice should be ordered from most derived to base.
    pub fn new(ids: &[ID]) -> Self {
        let mut chain = [ID::LAST; MAX_PROTO_CHAIN_LENGTH];
        let depth = ids.len().min(MAX_PROTO_CHAIN_LENGTH);
        
        for (i, &id) in ids.iter().take(depth).enumerate() {
            chain[i] = id;
        }
        
        InterfaceChain {
            chain,
            depth: depth as u8,
        }
    }
    
    /// Check if this interface chain contains the given ID.
    pub fn contains(&self, id: ID) -> bool {
        self.chain[..self.depth as usize].contains(&id)
    }
    
    /// Get the most derived interface ID.
    pub fn most_derived(&self) -> Option<ID> {
        if self.depth > 0 {
            Some(self.chain[0])
        } else {
            None
        }
    }
    
    /// Get the base interface ID.
    pub fn base(&self) -> Option<ID> {
        if self.depth > 0 {
            Some(self.chain[self.depth as usize - 1])
        } else {
            None
        }
    }
}

impl Default for InterfaceChain {
    fn default() -> Self {
        InterfaceChain {
            chain: [ID::LAST; MAX_PROTO_CHAIN_LENGTH],
            depth: 0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_id_operations() {
        let id = ID::new(42);
        assert_eq!(id.as_u16(), 42);
        assert!(!id.is_last());
        assert!(ID::LAST.is_last());
    }
    
    #[test]
    fn test_constructor_id() {
        let ctor = Constructor::new(100);
        assert_eq!(ctor.as_u16(), 100);
    }
    
    #[test]
    fn test_interface_chain() {
        // HTMLDivElement -> HTMLElement -> Element -> Node -> EventTarget
        let chain = InterfaceChain::new(&[
            well_known::HTML_DIV_ELEMENT,
            well_known::HTML_ELEMENT,
            well_known::ELEMENT,
            well_known::NODE,
            well_known::EVENT_TARGET,
        ]);
        
        assert_eq!(chain.depth, 5);
        assert_eq!(chain.most_derived(), Some(well_known::HTML_DIV_ELEMENT));
        assert_eq!(chain.base(), Some(well_known::EVENT_TARGET));
        assert!(chain.contains(well_known::ELEMENT));
        assert!(!chain.contains(well_known::DOCUMENT));
    }
    
    #[test]
    fn test_proto_id_to_name() {
        assert_eq!(proto_id_to_name(well_known::NODE.0), "Node");
        assert_eq!(proto_id_to_name(well_known::ELEMENT.0), "Element");
        assert_eq!(proto_id_to_name(well_known::DOCUMENT.0), "Document");
    }
    
    #[test]
    fn test_dynamic_allocation() {
        let initial = proto_count();
        let id1 = allocate_proto_id();
        let id2 = allocate_proto_id();
        
        assert_eq!(id2, id1 + 1);
        assert_eq!(proto_count(), initial + 2);
    }
}
